#!/bin/bash

# ============================================================
# ShopSmart Pro - SSL Setup with Let's Encrypt
# Usage: ./ssl-setup.sh yourdomain.com admin@yourdomain.com
# ============================================================

set -e

DOMAIN=${1:-"shopsmart.pro"}
EMAIL=${2:-"admin@shopsmart.pro"}
NGINX_CONF="/etc/nginx"
CERTBOT_DIR="/etc/letsencrypt"

echo "============================================"
echo "ShopSmart Pro - SSL Setup"
echo "Domain: $DOMAIN"
echo "Email: $EMAIL"
echo "============================================"

# Install Certbot if not present
install_certbot() {
    echo "Installing Certbot..."
    
    if command -v apt-get &> /dev/null; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    elif command -v yum &> /dev/null; then
        yum install -y certbot python3-certbot-nginx
    else
        echo "Package manager not supported. Please install certbot manually."
        exit 1
    fi
    
    echo "Certbot installed successfully"
}

# Generate SSL certificate
generate_certificate() {
    echo "Generating SSL certificate..."
    
    certbot certonly \
        --nginx \
        --non-interactive \
        --agree-tos \
        --email $EMAIL \
        --domains $DOMAIN,www.$DOMAIN,api.$DOMAIN,n8n.$DOMAIN \
        --expand
    
    echo "SSL certificate generated successfully"
}

# Generate strong DH parameters
generate_dhparam() {
    echo "Generating DH parameters (this may take a while)..."
    
    if [ ! -f "$NGINX_CONF/ssl/dhparam.pem" ]; then
        mkdir -p $NGINX_CONF/ssl
        openssl dhparam -out $NGINX_CONF/ssl/dhparam.pem 2048
    fi
    
    echo "DH parameters generated"
}

# Setup auto-renewal
setup_renewal() {
    echo "Setting up auto-renewal..."
    
    # Add renewal hook
    cat > /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh << 'EOF'
#!/bin/bash
nginx -t && systemctl reload nginx
EOF
    
    chmod +x /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh
    
    # Test renewal
    certbot renew --dry-run
    
    echo "Auto-renewal configured"
}

# Create Nginx SSL configuration
create_nginx_ssl_conf() {
    echo "Creating Nginx SSL configuration..."
    
    cat > $NGINX_CONF/ssl/ssl.conf << EOF
# SSL Configuration for ShopSmart Pro
# Generated by ssl-setup.sh

# SSL Certificates
ssl_certificate $CERTBOT_DIR/live/$DOMAIN/fullchain.pem;
ssl_certificate_key $CERTBOT_DIR/live/$DOMAIN/privkey.pem;
ssl_trusted_certificate $CERTBOT_DIR/live/$DOMAIN/chain.pem;

# SSL Settings
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

# DH Parameters
ssl_dhparam $NGINX_CONF/ssl/dhparam.pem;

# Modern SSL Configuration
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# HSTS (2 years)
add_header Strict-Transport-Security "max-age=63072000" always;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
EOF
    
    echo "SSL configuration created at $NGINX_CONF/ssl/ssl.conf"
}

# Create production Nginx configuration
create_nginx_server_conf() {
    echo "Creating Nginx server configuration..."
    
    cat > $NGINX_CONF/sites-available/shopsmart << EOF
# ShopSmart Pro - Production Nginx Configuration

# Rate limiting zones
limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=login_limit:10m rate=1r/s;

# Upstream servers
upstream backend {
    server 127.0.0.1:5000 weight=5;
    keepalive 32;
}

upstream frontend {
    server 127.0.0.1:3000;
}

upstream n8n {
    server 127.0.0.1:5678;
}

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN api.$DOMAIN n8n.$DOMAIN;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# Main Frontend
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;
    
    include $NGINX_CONF/ssl/ssl.conf;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.$DOMAIN wss://api.$DOMAIN;" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
    
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        
        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            proxy_pass http://frontend;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}

# API Server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name api.$DOMAIN;
    
    include $NGINX_CONF/ssl/ssl.conf;
    
    # Security headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Request size limits
    client_max_body_size 10M;
    
    location / {
        # Rate limiting
        limit_req zone=api_limit burst=20 nodelay;
        
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 90s;
        proxy_connect_timeout 90s;
    }
    
    location /api/auth {
        # Stricter rate limiting for auth endpoints
        limit_req zone=login_limit burst=5 nodelay;
        
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    
    # Health check (no rate limiting)
    location /api/health {
        proxy_pass http://backend;
        access_log off;
    }
}

# n8n Automation
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name n8n.$DOMAIN;
    
    include $NGINX_CONF/ssl/ssl.conf;
    
    location / {
        proxy_pass http://n8n;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }
}
EOF
    
    # Enable site
    ln -sf $NGINX_CONF/sites-available/shopsmart $NGINX_CONF/sites-enabled/
    
    # Test configuration
    nginx -t
    
    echo "Nginx configuration created"
}

# Main execution
main() {
    install_certbot
    generate_dhparam
    generate_certificate
    create_nginx_ssl_conf
    create_nginx_server_conf
    setup_renewal
    
    # Reload Nginx
    systemctl reload nginx
    
    echo ""
    echo "============================================"
    echo "SSL Setup Complete!"
    echo "============================================"
    echo ""
    echo "Your sites are now available at:"
    echo "  - https://$DOMAIN"
    echo "  - https://api.$DOMAIN"
    echo "  - https://n8n.$DOMAIN"
    echo ""
    echo "SSL certificates will auto-renew via certbot"
    echo "============================================"
}

main "$@"
